services:
    tt-bot-devcontainer:
        network_mode: host
        image: tt-bot-devcontainer
        container_name: tt-bot-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
            - $HOME/.ssh/:/home/vscode/.ssh:ro
            - $HOME/.gitconfig:/home/vscode/.gitconfig:ro
        env_file:
            - ../.env
            - ../.secrets/.env
        # This keeps the devcontainer running.
        entrypoint: [ "tail", "-f", "/dev/null" ]
