services:
    tt-bot-devcontainer:
        network_mode: host
        image: tt-bot-devcontainer
        container_name: tt-bot-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
        env_file:
            - ../.env
            - ../.secrets/.env
        # This keeps the devcontainer running.
        entrypoint: [ "tail", "-f", "/dev/null" ]
